# Tarea 1 Python

### Integrantes:

- Jorge Miyoshi Mikami Alonso
- Luis Manuel Reyes Colín


## Ejercicio 1

Con numpy, genera un array de 50 números aleatorios entre 0 y 1.

Calcula la media, la mediana y la desviación estándar de ese array.

Redondea los resultados a dos decimales e imprime cada valor.


In [27]:
import numpy as np

random_generator = np.random.default_rng()
array = random_generator.random(50)
print("Array:\n", array.round(2), "\n")

print("Media:", f"{array.mean():.2f}")
print("Mediana:", f"{np.median(array):.2}")
print("Desviación estándar:", f"{array.std():.2f}")

Array:
 [0.47 0.79 0.35 0.52 0.24 0.23 0.18 0.21 0.54 0.88 0.05 0.36 0.77 0.51
 0.59 0.41 0.8  0.43 0.57 0.06 0.17 0.12 0.98 0.22 0.49 0.41 0.17 0.68
 0.86 0.36 0.3  0.12 0.67 0.87 0.73 0.49 0.87 0.62 0.36 0.4  0.74 0.77
 0.8  0.45 0.56 0.35 0.56 0.95 0.42 0.21] 

Media: 0.49
Mediana: 0.48
Desviación estándar: 0.25


## Ejercicio 2

Crea una lista con los números del 1 al 20.

Usando una comprensión de listas, genera otra lista con el cuadrado de cada número.

Filtra la lista para quedarte únicamente con los números cuadrados mayores a 100.


In [28]:
nums = [i for i in range(1, 21)]
print("Lista del 1 al 20:\n", nums)

squares = [n**2 for n in nums]
print("Cuadrados de cada número:\n", squares)

squares_over_100 = [s for s in squares if s > 100]
print("Cuadrados mayores a 100:\n", squares_over_100)

Lista del 1 al 20:
 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
Cuadrados de cada número:
 [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]
Cuadrados mayores a 100:
 [121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


## Ejercicio 3

Crea dos matrices (arrays 2D) de tamaño 3x3 con valores enteros definidos manualmente o generados aleatoriamente.

Realiza la multiplicación matricial entre ellas.


In [29]:
matrix_one = np.array([[1, 2, 3], [2, 5, 4], [3, 6, 8]])
matrix_two = np.array([[7, 8, 9], [1, 2, 3], [5, 5, 5]])

multiplication = matrix_one @ matrix_two
print(multiplication)

[[24 27 30]
 [39 46 53]
 [67 76 85]]


## Ejercicio 4

Define una función que reciba un número entero positivo y devuelva:

"Par" si el número es par,

"Impar" si es impar,

Añade un mensaje de error si el número no es válido.


In [30]:
def even_or_odd(number):
    if not isinstance(number, int) or number <= 0:
        return "Número no valido"
    return "Par" if number % 2 == 0 else "Impar"


print(even_or_odd(2))

Par


## Ejercicio 5

Elabora un programa que sea capaz de calcular el IMC (Índice de masa corporal) de una persona. Los datos deberán ser ingresados por el usuario.

El IMC se calcula dividiendo los kilogramos de peso de una persona por el cuadrado de su estatura en metros (IMC = peso [kg]/ (estatura^2) [m2]).


In [31]:
def imc(peso, estatura):
    return f"Tu IMC es {peso / estatura**2:.3f}"


peso = float(input("Introduce tu peso en kilogramos: "))
estatura = float(input("Introduce tu estatura en metros: "))

imc(peso, estatura)

'Tu IMC es 25.690'