## Ejercicio 1
Con numpy, genera un array de 50 números aleatorios entre 0 y 1.

Calcula la media, la mediana y la desviación estándar de ese array.

Redondea los resultados a dos decimales e imprime cada valor.

In [ ]:
import numpy as np
rnd = np.random.rand(50)
mean_rnd = np.round(np.mean(rnd),2)
median_rnd = np.round(np.median(rnd),2)
std_rnd= np.round(np.std(rnd),2)
print(rnd)
print("Media:", f"{mean_rnd:.2f}")
print("Mediana:", f"{median_rnd:.2f}")
print("Desviación estándar:", f"{std_rnd:.2f}")

[0.36337432 0.45432945 0.22500185 0.07892225 0.37304906 0.63282272
 0.15421243 0.16533501 0.90162076 0.55957403 0.68815061 0.31085866
 0.47610234 0.6831296  0.74494503 0.85129258 0.42946162 0.87530635
 0.87832471 0.98824681 0.72139523 0.95148065 0.13022989 0.00791128
 0.9768827  0.57724407 0.15833912 0.22550107 0.99085599 0.78924448
 0.93506697 0.46559066 0.53293629 0.69239015 0.75165384 0.56993012
 0.26025177 0.83951421 0.40633208 0.6767638  0.24922429 0.19537256
 0.73769036 0.01695577 0.51923218 0.39906045 0.5329177  0.49654605
 0.92246644 0.37271495]
Media: 0.54
Mediana: 0.53
Desviación estándar: 0.28


## Ejercicio 2
Crea una lista con los números del 1 al 20.

Usando una comprensión de listas, genera otra lista con el cuadrado de cada número.

Filtra la lista para quedarte únicamente con los números cuadrados mayores a 100.

In [ ]:
import numpy as np
vect = list()
vect_Square = list()
for i in range(21):
    j = i + 1
    vect.append(j)
print(vect)
for i in range(21):
    j = i +1
    vect_Square.append(vect[i]**2)
print(vect_Square)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441]


## Ejercicio 3
Crea dos matrices (arrays 2D) de tamaño 3x3 con valores enteros definidos manualmente o generados aleatoriamente.

Realiza la multiplicación matricial entre ellas.

In [ ]:
import numpy as np
matrix_rnd = np.random.rand(3,3)
print("A", matrix_rnd)
matrix_rnd2 = np.random.rand(3,3)
print("B", matrix_rnd2)
matrix_mult = np.dot(matrix_rnd, matrix_rnd2)
print("Multiplicación:", matrix_mult)
#

A [[0.28527681 0.67226336 0.56220409]
 [0.4506151  0.85108787 0.79911662]
 [0.20403687 0.45645033 0.30454088]]
B [[0.56115582 0.06517028 0.45285018]
 [0.37453004 0.46159059 0.97625045]
 [0.02738462 0.76320678 0.22700326]]
Multiplicación: [[0.42726331 0.75797998 0.91310723]
 [0.59350677 1.03211208 1.21633812]
 [0.29379057 0.45641797 0.60713974]]


##Ejercicio 4
Define una función que reciba un número entero positivo y devuelva:

"Par" si el número es par,

"Impar" si es impar,

Añade un mensaje de error si el número no es válido.

In [ ]:
def Chi(a):
    try:
        num = int(a)
        if num <= 0:
            print("El numero no es valido (debe ser un entero positivo)")
        elif num % 2 == 1:
            print("Impar")
        else:
            print("Par")
    except ValueError:
        print("El numero no es valido (no es un entero)")

Chi(input())

1212
Par


##Ejercicio 5
Elabora un programa que sea capaz de calcular el IMC (Índice de masa corporal) de una persona. Los datos deberán ser ingresados por el usuario.

El IMC se calcula dividiendo los kilogramos de peso de una persona por el cuadrado de su estatura en metros (IMC = peso [kg]/ (estatura^2) [m2]).

In [ ]:
import numpy as np
import pandas as pd
def IMC(peso, estatura):
    peso = float(peso)
    estatura = float(estatura)
    IMC_value = peso / estatura**2

    print(IMC_value)

IMC(input(), input())

123
1231
8.116877760480836e-05
